/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.text.NumberFormat;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import model.bean.Venda;
import modelo_query.dao.VendaDAO;

/**
 *
 * @author 963478
 */
public class tela_6 extends javax.swing.JFrame {

    /**
     * Creates new form tela_6
     */
    public tela_6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DINHEIRO = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pagamentos = new javax.swing.JLabel();
        aparece = new javax.swing.JLabel();
        ver = new javax.swing.JLabel();
        dinheiro = new javax.swing.JLabel();
        cartao = new javax.swing.JLabel();
        cheque = new javax.swing.JLabel();
        troco = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        obs = new javax.swing.JLabel();
        obsField = new javax.swing.JTextField();
        trocoField = new javax.swing.JTextField();
        dinheiroField = new javax.swing.JTextField();
        cartaoField = new javax.swing.JTextField();
        chequeField = new javax.swing.JTextField();
        valorDadoField = new javax.swing.JTextField();
        finalizar = new javax.swing.JButton();
        calcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalField = new javax.swing.JTextField();
        total1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        DINHEIRO.setBackground(new java.awt.Color(255, 255, 255));
        DINHEIRO.setForeground(new java.awt.Color(255, 255, 255));
        DINHEIRO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 105, 255));

        pagamentos.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        pagamentos.setForeground(new java.awt.Color(255, 255, 255));
        pagamentos.setText("Pagamentos");

        aparece.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ver.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ver.setText("Ver Histórico");
        ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(pagamentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(aparece, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ver, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(pagamentos)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aparece, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(ver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        DINHEIRO.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, -1));

        dinheiro.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        dinheiro.setText("DINHEIRO:");
        DINHEIRO.add(dinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        cartao.setBackground(new java.awt.Color(0, 0, 0));
        cartao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cartao.setText("CARTÃO:");
        DINHEIRO.add(cartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        cheque.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cheque.setText("CHEQUE:");
        DINHEIRO.add(cheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        troco.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        troco.setText("VALOR DADO:");
        DINHEIRO.add(troco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        total.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        total.setText("TROCO:");
        DINHEIRO.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        obs.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        obs.setText("Obs.:");
        DINHEIRO.add(obs, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 166, -1, -1));

        obsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obsFieldActionPerformed(evt);
            }
        });
        DINHEIRO.add(obsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 164, 330, 130));

        trocoField.setEditable(false);
        DINHEIRO.add(trocoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 100, 30));
        DINHEIRO.add(dinheiroField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, 30));
        DINHEIRO.add(cartaoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 150, 30));
        DINHEIRO.add(chequeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 150, 30));
        DINHEIRO.add(valorDadoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 150, 30));

        finalizar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        finalizar.setText("Finalizar Venda");
        finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarActionPerformed(evt);
            }
        });
        DINHEIRO.add(finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 190, 40));

        calcular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        DINHEIRO.add(calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 170, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("-");
        DINHEIRO.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 30, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("+");
        DINHEIRO.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 30, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("+");
        DINHEIRO.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 30, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("+");
        DINHEIRO.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 30, 20));

        totalField.setEditable(false);
        DINHEIRO.add(totalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 100, 30));

        total1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        total1.setText("TOTAL:");
        DINHEIRO.add(total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DINHEIRO, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DINHEIRO, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void obsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obsFieldActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        // TODO add your handling code here:
        NumberFormat z = NumberFormat.getCurrencyInstance();
        double a, b, c, d, total1, total2;
        a = Double.parseDouble(dinheiroField.getText());
        b = Double.parseDouble(cartaoField.getText());
        c = Double.parseDouble(chequeField.getText());
        d = Double.parseDouble(valorDadoField.getText());
        total1 = a + b + c;
        total2 = d - (a + b + c);
        totalField.setText(String.valueOf(z.format(total1)));
        trocoField.setText(String.valueOf(z.format(total2)));
    }//GEN-LAST:event_calcularActionPerformed

    private void finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarActionPerformed
        // TODO add your handling code here:

        Date dataAtual = new Date();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String dataFormatada = dateFormat.format(dataAtual);

        double a, b, c, totalzin;
        a = Double.parseDouble(dinheiroField.getText());
        b = Double.parseDouble(cartaoField.getText());
        c = Double.parseDouble(chequeField.getText());
        totalzin = a + b + c;
        String obser = obsField.getText();

        Venda oi = new Venda();
        VendaDAO oi2 = new VendaDAO();
        oi.setData(dataFormatada);
        oi.setValor(totalzin);
        oi.setObs(obser);
        oi2.criarAmigo(oi);

        dinheiroField.setText("");
        cartaoField.setText("");
        chequeField.setText("");
        totalField.setText("");
        valorDadoField.setText("");
        trocoField.setText("");
        obsField.setText("");


    }//GEN-LAST:event_finalizarActionPerformed

    private void verMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMouseClicked
        // TODO add your handling code here:
        tela_3 form2 = new tela_3();
        form2.setVisible(true);
    }//GEN-LAST:event_verMouseClicked

    private void verMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_verMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DINHEIRO;
    private javax.swing.JLabel aparece;
    private javax.swing.JButton calcular;
    private javax.swing.JLabel cartao;
    private javax.swing.JTextField cartaoField;
    private javax.swing.JLabel cheque;
    private javax.swing.JTextField chequeField;
    private javax.swing.JLabel dinheiro;
    private javax.swing.JTextField dinheiroField;
    private javax.swing.JButton finalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel obs;
    private javax.swing.JTextField obsField;
    private javax.swing.JLabel pagamentos;
    private javax.swing.JLabel total;
    private javax.swing.JLabel total1;
    private javax.swing.JTextField totalField;
    private javax.swing.JLabel troco;
    private javax.swing.JTextField trocoField;
    private javax.swing.JTextField valorDadoField;
    private javax.swing.JLabel ver;
    // End of variables declaration//GEN-END:variables
}
